config/routes.rb
Etsydemo::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :subjects

  resources :tutorships do
    collection do
      put :accept_tutorship, as: 'accept'
    end
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  resources :questions do
    collection do
      post "create_question_comment" do
        post "create_question_comment_reply"
      end
    end
  end

  scope "(:locale)", locale: /en|ko|zh/ do
    
    resources :messages 

    resources :conversations do
      member do
        post :reply
        post 'trash'
      end
    end
    
    devise_for :users, :path_prefix => 'account', :controllers => { :registrations => "registrations" }
   
    resources :tutor_profiles do 
      get :autocomplete_tutor_profile_teaching_subject, :on => :collection
      collection do 
        get 'search'
        get 'reference'
        get 'invite_for_review'
        post 'send_invitation_for_review'
        get 'send_user_specific_request_for_review'
      end
      
      resources :tuitions do
        collection do
          get 'book_tuition'
          get 'payment_detail'
          post 'perform_transaction'
        end
      end
      resources :reviews, except: [:show, :index]
    end

    resources :new_tutor_profiles do
      collection do
        post 'update_tutor_profile'
      end
    end
  
    resources :enquiries 
    
    resources :users
  end

  get "pages/about"
  get 'mytuition' => "tuitions#mytuition"
  get "pages/inbox"
  get "pages/resources"
  get "pages/personal_statements"
  get "pages/college_essays"
  get "pages/oxbridge_interview_questions"
  get "pages/suggested_readings"
  get "pages/admissions_facts"
  get "pages/writing_personal_statements"
  get "pages/admissions_test"
  get "pages/written_work"
  get "pages/oxbridge_interviews"
  get "pages/students_parents"
  get "pages/services_for_schools"
  get "pages/partners"
  
  get "pages/how_it_works"
  get "pages/terms_and_conditions"
  get "pages/terms_and_conditions/for_tutors"
  get "pages/terms_and_conditions/for_students"
  get "pages/become_a_tutor"
  get "pages/referral_scheme"
  get "pages/tutor_policy"
  get "pages/free_consultation"
  get "pages/our_stars"
  get "pages/recruiting"
  get "pages/us_admissions"
  
  get "pages/about"
  get "pages/language_learning"
  get "pages/examinations"
  get "pages/online_tuition"
  get "pages/our_tutors"
  
  
  post "pages/get_town_from_country_for_step_1"
  post "pages/get_country_set_city"
  post "pages/get_city_set_town"
  
  get "admin/notify_users"
  post "admin/send_mail_to_users"
  get "admin/run_script"

  root 'pages#index'

  

end

app/models/tutorship.rb
class Tutorship < ActiveRecord::Base
  belongs_to :user
  belongs_to :tutor_profile
  validates :terms_of_service, acceptance: true

  
# scopes defined as class methods
  class << self

    def accepted
      where(accepted: true)
    end

    def rejected
      where(accepted: false)
    end

    def pending
      where("tutorships.accepted IS NULL")
    end

    def pending_invites_from_student
      pending.where(created_by_student: true)
    end

    def rejected_invites_from_student
      rejected.where(created_by_student: true)
    end

  end 
end

app/controllers/tutorships_controller.rb
class TutorshipsController < ApplicationController
  before_action :set_tutorship, only: [:show, :edit, :update, :destroy]
  

  def tutors
    @tutorships = Tutorship.all
  end
  
  def students
    @tutorships = Tutorship.all
  end
  
  # GET /tutorships
  # GET /tutorships.json
  def index
    @tutorships = Tutorship.all
  end

  # GET /tutorships/1
  # GET /tutorships/1.json
  def show
  end

  # GET /tutorships/new
  def new
    @tutorship = Tutorship.new
  end

  # GET /tutorships/1/edit
  def edit
    
    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        :amount => (@tutorship.tuition_fee * 100).floor,
        :currency => "usd",
        :card => token
        )
      flash[:notice] = "Thanks for booking!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end
    
  end

  
  # POST /tutorships
  # POST /tutorships.json
  def create
    @tutorship = Tutorship.new(tutorship_params)
    
    @tutorship.user_id = current_user.id
    @tutor_profile = User.find(params[:tutor_profile]) #tutor__profile id in the tutorship table equals the tutor__profile_id of the tutor_profile student is on 
    respond_to do |format|
      if @tutorship.save
        format.html { redirect_to @tutorship, notice: 'Tutorship was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tutorship }
      else
        format.html { render action: 'new' }
        format.json { render json: @tutorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorships/1
  # PATCH/PUT /tutorships/1.json
  def update
    respond_to do |format|
      if @tutorship.update(params[:tutor_profile])
        format.html { redirect_to @tutorship, notice: 'Tutorship was successfully accepted.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tutorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorships/1
  # DELETE /tutorships/1.json
  def destroy
    @tutorship.destroy
    respond_to do |format|
      format.html { redirect_to tutorships_url }
      format.json { head :no_content }
    end
  end
  
    def invite_to_tutorship
    @tutor_profile = User.find(params[:tutor__profile_id] )
    @user = current_user
    @enquiry = current_user.enquiries.last
    @tutor_profile.pending_invites_to_be_a_tutor.create(subject: @enquiry.subject, message: @enquiry.note,  user_id: current_user.id, status: :invited)
 
    redirect_to :tutor_profiles
  end

  def accept_tutorship
    @tutorship = Tutorship.find(params[:id])
    accepted_tutorship = @tutorship.update(accepted: true)
    
    redirect_to :tutor_profiles    
  end
  
private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorship
      @tutorship = Tutorship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorship_params
      params.require(:tutorship).permit(:tutor_profile_id, :user_id, :accepted, :created_by_student, :starting_date, :hourly_rate, :hours_a_week, :weeks, :tuition_fee)
    end
end

app/helpers/tutorships_helper.rb
module TutorshipsHelper
end

app/views/tutorships/_form.html.erb
<%= form_for(@tutorship) do |f| %>
  <% if @tutorship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorship.errors.count, "error") %> prohibited this tutorship from being saved:</h2>

      <ul>
      <% @tutorship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :starting_date %><br>
          <%= f.text_field :starting_date, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :hourly_rate %><br>
          <%= f.number_field :hourly_rate, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :hours_a_week %><br>
          <%= f.number_field :hours_a_week, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :weeks %><br>
          <%= f.number_field :weeks, class: "form-control" %>
        </div>
      </div>  
      <div class="form-group">
          <%= check_box_tag '' %> I have read and agree to <a href="/pages/terms_and_conditions">Terms and Conditions</a> set by Young Tutors
      </div>  
      <div class="actions">
        <%= f.submit "Request Tutorship", class: "btn btn-success" %>
      </div>
    </div><!-- end of row -->
  </div>
</div>

<% end %> 

app/views/tutorships/edit.html.erb
<%= form_for(@tutorship) do |f| %>
  <% if @tutorship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorship.errors.count, "error") %> prohibited this tutorship from being saved:</h2>

      <ul>
      <% @tutorship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <h1>Payment</h1>
    <p>I agree to the following charge being made for tutorship I have requested.</p><br>
    <p>Tutorship with <% tutor_profile = TutorProfile.find(@tutorship.tutor_profile_id)
      user = User.find(tutor_profile.user_id) %><b style="font-size: 20px"><%= user.first_name %> <%= user.last_name %></b> for tuition fee of <b style="font-size: 20px">£<%= @tutorship.tuition_fee %></b>
    </p><br>
      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>
       <div class="form-group">
          <div class="row">
            <div class="col-md-8">
              <%= label_tag :card_number, "Credit Card Number" %>
              <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
            </div>
            <div class="col-md-4">
              <%= label_tag :card_code, "CVC" %>
              <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= label_tag nil, "Expiration Date" %>
          <div class="row">
            <div class="col-md-3">
              <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
            </div>
            <div class="col-md-3">
              <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit "Complete Order", class: "btn btn-success" %>
        </div>
      <% end %> 
  </div>
  </div>


      <br><br>
      <div class="row">
        <div class="col-md-6 col-md-offset-2">
          <div class="right">
          <%= link_to 'Review tutorship before payment', @tutorship, class: "btn btn-primary" %>
          </div>
        </div>
        </div>

app/views/tutorships/index.html.erb
<h1>Admin</h1>

<table class="table">
  <thead>
    <tr>
      <th>Tutor</th>
      <th>Student</th>
      <th>Subject</th>
      <th>Accepted</th>
      <th>Starting date</th>
      <th>Hourly Rate</th>
      <th>hours/week</th>
      <th>Weeks</th>
      <th>Tuition Fee</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorships.each do |tutorship| %>
      <tr>
        <td><% 
  tutor_profile = TutorProfile.find(tutorship.tutor_profile_id) 
  user = User.find(tutor_profile.user_id) 
  %>
        <%= user.first_name %> </td>
        <td><% user = User.find(tutorship.user_id) %><%= user.first_name %></td>
        <td><%= tutorship.accepted %></td>
        <td><%= tutorship.starting_date %></td>
        <td><%= tutorship.hourly_rate %></td>
        <td><%= tutorship.hours_a_week %></td>
        <td><%= tutorship.weeks %></td>
        <td><%= tutorship.tuition_fee %></td>
        <td></td>
        <td></td>
        <td><%= link_to 'Show', tutorship %></td>
        <td><%= link_to 'Edit', edit_tutorship_path(tutorship) %></td>
        <td><%= link_to 'Destroy', tutorship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutorship', new_tutorship_path %>

app/views/tutorships/new.html.erb
<h1>New tutorship</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorships_path %>

app/views/tutorships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accepted:</strong>
  <%= @tutorship.accepted %>
</p>

<p>
  <strong>Starting date:</strong>
  <%= @tutorship.starting_date %>
</p>
<p>
  <strong>Hourly Rate:</strong>
  <%= @tutorship.hourly_rate %>
</p>
<p>
  <strong>hr/week:</strong>
  <%= @tutorship.hours_a_week %>
</p>
<p>
  <strong>Weeks:</strong>
  <%= @tutorship.weeks %>
</p>

<p>
  <strong>Tuition Fee:</strong>
  <%= @tutorship.tuition_fee %>
</p>

<%= link_to 'Edit', edit_tutorship_path(@tutorship) %> |
<%= link_to 'Back', tutorships_path %>

app/views/tutorships/students.html.erb
<div class="centre">
  <h2>Student Page</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Tutor</th>
    <th class="center">Starting Date</th>
    <th class="center">Status</th>
    <th class="center">Payment</th>
    <th class="center">Review</th>
    <th class="center">Accept</th>
    


  </tr>
   <!-- using the tutor_id from tutorial_reqeust table, find user_id to find user first and last names -->
  <!--
    @tutor = Tutor.find(tutorial_request.tutor_id)
    @user = User.find(tutor.user_id) 
 -->

  <% @tutorships.each do |tutorship| %>
    <tr>
      <td class="center"><% 
  tutor_profile = TutorProfile.find(tutorship.tutor_profile_id) 
  user = User.find(tutor_profile.user_id) 
  %>
        <%= user.first_name %> </td>
      <td class="center"><%= tutorship.starting_date%></td>   
      <td class="center">
        Pending<!-- the status has to change depending on time period written in tutorial request form -->
        in process<br><!-- if tutor's status is 'I'm available' and request is made -->
        complete <!-- at the end of tutorship duration -->
      </td>
      <td class="center">
        
        <%= link_to "Pay Now",  edit_tutorship_path(tutorship), data: { no_turbolink: true } %>
        
      </td>
      <td class="center">
        write a review <!-- write a review function becomes active if status is complete, direct to new_tutor_review_path where the tutor ID matches otherwise, review field is left blank-->
      </td>
      <td class="center">
        <%= link_to "Accept",  accept_tutorships_path, method: :put %>
      </td>

    </tr>
  <% end %>
</table>

<br>

app/views/tutorships/tutors.html.erb
<div class="centre">
  <h2>My Tutor History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Student Name</th>
    <th class="center">Starting Date</th>
    <th class="center">Duration</th>
    <th class="center">Status</th>
    <th class="center">Bill</th>

  </tr>
  <% @tutorships.each do |tutorship| %>
    <tr>
      <td class="center"><% user = User.find(tutorship.user_id) %><%= user.first_name %></td> 
      <td class="center"><%= tutorship.starting_date %></td>  
      <td class="center"><%= tutorship.duration %></td>  
      <td class="center">
        Pending<!-- the status has to change depending on time period written in tutorial request form -->
        in process<br><!-- if tutor's status is 'I'm available' and request is made -->
        complete <!-- at the end of tutorship duration -->
      </td>
      <td class="center">
        Bill Now
        <%= link_to "Accept", tutorship_path, :method => :patch %>
  
      </td>
    </tr>
  <% end %>
</table>

<br>