config/routes.rb
Etsydemo::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :subjects

  resources :tutorships do
    collection do
      put :accept_tutorship, as: 'accept'
    end
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  resources :questions do
    collection do
      post "create_question_comment" do
        post "create_question_comment_reply"
      end
    end
  end

  scope "(:locale)", locale: /en|ko|zh/ do
    
    resources :messages 

    resources :conversations do
      member do
        post :reply
        post 'trash'
      end
    end
    
    devise_for :users, :path_prefix => 'account', :controllers => { :registrations => "registrations" }
   
    resources :tutor_profiles do 
      get :autocomplete_tutor_profile_teaching_subject, :on => :collection
      collection do 
        get 'search'
        get 'reference'
        get 'invite_for_review'
        post 'send_invitation_for_review'
        get 'send_user_specific_request_for_review'
      end
      
      resources :tuitions do
        collection do
          get 'book_tuition'
          get 'payment_detail'
          post 'perform_transaction'
        end
      end
      resources :reviews, except: [:show, :index]
    end

    resources :new_tutor_profiles do
      collection do
        post 'update_tutor_profile'
      end
    end
  
    resources :enquiries 
    
    resources :users
  end

  get "pages/about"
  get 'mytuition' => "tuitions#mytuition"
  get "pages/inbox"
  get "pages/resources"
  get "pages/personal_statements"
  get "pages/college_essays"
  get "pages/oxbridge_interview_questions"
  get "pages/suggested_readings"
  get "pages/admissions_facts"
  get "pages/writing_personal_statements"
  get "pages/admissions_test"
  get "pages/written_work"
  get "pages/oxbridge_interviews"
  get "pages/students_parents"
  get "pages/services_for_schools"
  get "pages/partners"
  
  get "pages/how_it_works"
  get "pages/terms_and_conditions"
  get "pages/terms_and_conditions/for_tutors"
  get "pages/terms_and_conditions/for_students"
  get "pages/become_a_tutor"
  get "pages/referral_scheme"
  get "pages/tutor_policy"
  get "pages/free_consultation"
  get "pages/our_stars"
  get "pages/recruiting"
  get "pages/us_admissions"
  
  get "pages/about"
  get "pages/language_learning"
  get "pages/examinations"
  get "pages/online_tuition"
  get "pages/our_tutors"
  
  
  post "pages/get_town_from_country_for_step_1"
  post "pages/get_country_set_city"
  post "pages/get_city_set_town"
  
  get "admin/notify_users"
  post "admin/send_mail_to_users"
  get "admin/run_script"

  root 'pages#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  acts_as_messageable
  after_create :send_welcome_mail_to_user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true  

  has_one :tutor_profile, dependent: :destroy
  has_many :tuitions, dependent: :destroy
  has_many :enquiries, dependent: :destroy
  has_many :questions
  



  # User can be a student, a tutor or both and can have both the tuition and tutorial request records 
  # foreign key tells Rails to use the tutor_ID to figure out which user was the tutor for this tutorial request
  has_many :tutors, class_name: "Tutorship", foreign_key: "tutor_id"
  has_many :students, class_name: "Tutorship", foreign_key: "student_id"  
  has_many :reviews, dependent: :destroy

  def name
    email
  end

  def mailboxer_email(object)
    email
  end

  def send_welcome_mail_to_user
    WelcomeMailer.registration_confirmation(self).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, except: [:new, :create]

  respond_to :html, :json

  def index
     #Rails.logger.debug("index is: #{self.inspect}")
    @users = User.all
    respond_with(@users)
  end

  def show
    # Rails.logger.debug("show is: #{self.inspect}")
  end
  
  def edit
  end

  def new
    @user = User.new
  end
  def create
  
    @user = User.new(user_params)
   if @user.save
     sign_in @user
     redirect_to @user, {notice: 'Your account was created'}
   else
     render 'new'
   end

  end

  def update
    # required for settings form to submit when password is left blank
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end
    if @user.update(user_params)
      
      # Sign in the user by passing validation in case his password changed
      sign_in :user, @user, :bypass => true 
      redirect_to @user, {notice: 'Your Account details were updated'}
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_pth, {notice: 'Your account was deleted'}
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this email_template from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label 'Account Type' %><br>
    <%= f.collection_select :role, User::ROLE_OPTIONS, :to_s, :titleize %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br>

<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1> List of Users </h1>
<table>
  <thead>
   <tr>
    <th> First Name </th>
    <th> Last name </th>
    <th> Email </th>
   </tr>  
  <thead>
  <tbody>
   <% @users.each do |user| %>
   <tr>
     <td> <%= user.first_name %> </td>
     <td> <%= user.last_name %> </td>
     <td> <%= user.email %> </td>
     <% if check_current_user?(user) %>
     <td><%= link_to "Show", user_path(user) %> </td>
     <td><%= link_to "Edit", edit_user_path(user) %> </td>
     <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     <% end %>
   </tr>
     <% end %>
  <tbody

</table>

<br>
<p> <%= link_to "Create User", new_user_path %> </p>

<br>
<%= link_to 'Back', root_path %>
<br>

<p> <%= link_to "Add Account", new_user_registration_path %> </p>

app/views/users/new.html.erb
<%=  render "form" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>FirstName:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
<% if check_current_user?(@user) %>
  <div> <%= link_to "Edit", edit_user_path(@user) %>  </div>
  <br>
  <p><%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

<%= link_to 'Back list of users', users_path %>
<br>
<%= link_to 'Back to conversations', root_path %>
</p>