config/routes.rb
Etsydemo::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :subjects

  resources :tutorships do
    collection do
      put :accept_tutorship, as: 'accept'
    end
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  resources :questions do
    collection do
      post "create_question_comment" do
        post "create_question_comment_reply"
      end
    end
  end

  scope "(:locale)", locale: /en|ko|zh/ do
    
    resources :messages 

    resources :conversations do
      member do
        post :reply
        post 'trash'
      end
    end
    
    devise_for :users, :path_prefix => 'account', :controllers => { :registrations => "registrations" }
   
    resources :tutor_profiles do 
      get :autocomplete_tutor_profile_teaching_subject, :on => :collection
      collection do 
        get 'search'
        get 'reference'
        get 'invite_for_review'
        post 'send_invitation_for_review'
        get 'send_user_specific_request_for_review'
      end
      
      resources :tuitions do
        collection do
          get 'book_tuition'
          get 'payment_detail'
          post 'perform_transaction'
        end
      end
      resources :reviews, except: [:show, :index]
    end

    resources :new_tutor_profiles do
      collection do
        post 'update_tutor_profile'
      end
    end
  
    resources :enquiries 
    
    resources :users
  end

  get "pages/about"
  get 'mytuition' => "tuitions#mytuition"
  get "pages/inbox"
  get "pages/resources"
  get "pages/personal_statements"
  get "pages/college_essays"
  get "pages/oxbridge_interview_questions"
  get "pages/suggested_readings"
  get "pages/admissions_facts"
  get "pages/writing_personal_statements"
  get "pages/admissions_test"
  get "pages/written_work"
  get "pages/oxbridge_interviews"
  get "pages/students_parents"
  get "pages/services_for_schools"
  get "pages/partners"
  
  get "pages/how_it_works"
  get "pages/terms_and_conditions"
  get "pages/terms_and_conditions/for_tutors"
  get "pages/terms_and_conditions/for_students"
  get "pages/become_a_tutor"
  get "pages/referral_scheme"
  get "pages/tutor_policy"
  get "pages/free_consultation"
  get "pages/our_stars"
  get "pages/recruiting"
  get "pages/us_admissions"
  
  get "pages/about"
  get "pages/language_learning"
  get "pages/examinations"
  get "pages/online_tuition"
  get "pages/our_tutors"
  
  
  post "pages/get_town_from_country_for_step_1"
  post "pages/get_country_set_city"
  post "pages/get_city_set_town"
  
  get "admin/notify_users"
  post "admin/send_mail_to_users"
  get "admin/run_script"

  root 'pages#index'

  

end

app/models/tutor_profile.rb
class TutorProfile < ActiveRecord::Base
  #has_attached_file :image, :styles => { :medium => "200x200>", :small => "100x100#", :large => "500x500>" }, :class => "img-circle", :default_url => "default.jpg", :processors => [:cropper],
  					#:storage => :dropbox,
   					#:dropbox_credentials => Rails.root.join("config/dropbox.yml")
            # :default_url => "/images/:style/missing.png",
            # :path => "/:id/:style/:basename.:extension",
            # :url => "/system/:attachment/:id/:style/:basename.:extension"
  
  has_attached_file :image, :styles => { :medium => "200x200>", :small => "100x100#", :large => "500x500>" }, :class => "img-circle", :default_url => "default.jpg", :processors => [:cropper],
                    :storage => :s3,
                    :bucket => "gurumek.s3-ap-northeast-1.amazonaws.com",
                    :s3_credentials => "#{Rails.root}/config/s3.yml"

  validates :university, :hourly_rate, presence: true
  validates :terms_of_service, acceptance: true

  # --- Parameters for image copping
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  belongs_to :user
  has_many :tuitions
  has_many :reviews
  has_many :tutor_degree_subjects
  has_many :tutor_teaching_subjects
  
      # agreed tutorships where this user is the tutor
  has_many  :tutorships_as_tutor,
              ->{ Tutorship.accepted },
              class_name: "Tutorship",
  foreign_key: :tutor_profile_id

  # invites asking this user to be a tutor
  has_many  :pending_invites_to_be_a_tutor,
              ->{ Tutorship.pending_invites_from_student },
              class_name: "Tutorship",
  foreign_key: :tutor_profile_id

  # rejected invites asking this user to be a tutor
  has_many  :rejected_invites_to_be_a_tutor,
              ->{ Tutorship.rejected_invites_from_student },
              class_name: "Tutorship",
  foreign_key: :tutor_profile_id

  after_create :set_proper_visibility
  after_update :set_proper_visibility

  scope :filter_by_country, ->(country_name) { where("country = (?) OR location = (?)", country_name,country_name) }
  scope :filter_by_city, ->(city_name) { where("location_two = (?) OR location_city = (?)",city_name,city_name) }
  scope :filter_by_university, ->(university) { where(:university => university) }

  def self.get_all_subjects_with_levels(subject,levels)
    result_tutor_profiles = []
    self.all.each do |tp|
      if tp.visibility
        if tp.is_tutor_appropriate?(subject,levels)
          result_tutor_profiles << tp
        end
      end
    end
    return result_tutor_profiles
  end


  def self.get_matching_subject(subject)
    result_tutor_profiles = []
    self.all.each do |tp|
      if tp.visibility
        if tp.is_tutor_matching_subject?(subject)
          result_tutor_profiles << tp
        end
      end
    end
    return result_tutor_profiles
  end


  def self.get_matching_levels(level)
    result_tutor_profiles = []
    self.all.each do |tp|
      if tp.visibility
        if tp.is_tutor_matching_level?(level)
          result_tutor_profiles << tp
        end
      end
    end
    return result_tutor_profiles
  end


  def is_tutor_matching_subject?(subject)
    degree_subjects = []
    teaching_subjects = []
    #  Search in degree subjects
    degree_subjects = self.tutor_degree_subjects.pluck(:degree_subject)
    teaching_subjects = self.tutor_teaching_subjects.pluck(:teaching_subject)

    all_subjects = degree_subjects+teaching_subjects
    if all_subjects.include?(subject)
      return true
    else
      return false
    end
  end


  def is_tutor_matching_level?(level)
    degree_levels = []
    teaching_levels = []
    #  Search in degree subjects
    degree_levels = self.tutor_degree_subjects.first.degree_subject_levels.where("level IN (?)",level).pluck(:level) rescue []

    self.tutor_teaching_subjects.each { |tts| teaching_levels = teaching_levels + tts.teaching_subject_levels.pluck(:level) }

    all_levels = degree_levels + teaching_levels

    if (all_levels & level).blank?
      return false
    else
      return true
    end
  end


  def is_tutor_appropriate?(subject,levels)
    degree_levels = []
    teaching_levels = []

    #  Search in degree subjects
    self.tutor_degree_subjects.where(:degree_subject => subject).each do |ds|
      degree_levels = ds.degree_subject_levels.pluck("level")
    end

    #  Search in teaching subjects
    self.tutor_teaching_subjects.where(:teaching_subject => subject).each do |ts|
      teaching_levels = ts.teaching_subject_levels.pluck("level")
    end

    all_levels = degree_levels + teaching_levels

    if all_levels.blank?
      return false
    else
      return (all_levels & levels).blank? ? false : true
    end
  end


  def levelwise_subjects
    if self.tutor_teaching_subjects.present?
      epl = Level.exam_preparation_levels
      tsl = {
          epl[0] => [],
          epl[1] => [],
          epl[2] => [],
          epl[3] => [],
          epl[4] => [],
          epl[5] => []
      }
      self.tutor_teaching_subjects.each do |tts|
        tts_levels = tts.teaching_subject_levels.pluck(:level)
        tsl.each do |k,v|
          if tts_levels.include?(k)
            v << tts.teaching_subject.capitalize
          end
        end
      end
      return tsl
    end
  end


  def set_proper_visibility
    tutor_profile = self
    vib = false
    if !(tutor_profile.university.nil?) #check presence of university
      if !(tutor_profile.tutor_degree_subjects.blank?) #check presence of degree subject
        if !(tutor_profile.tutor_degree_subjects.first.degree_subject_levels.blank?) #check presence of degree subjects' levels
          if !(tutor_profile.tutor_teaching_subjects.blank?) #check presence of teaching subject
            if !(tutor_profile.tutor_teaching_subjects.map{|tts| tts.teaching_subject_levels.blank? }.include?(true)) #check at least one level is present in all teaching subjects
              vib = true
            end
          end
        end
      end
    end
    unless tutor_profile.visibility==vib
      tutor_profile.update_attributes(:visibility => vib)
    end
  end

  def self.set_all_users_visibility_script
    self.all.each do |tp|
      tp.set_proper_visibility
    end
  end

  def self.enable_all_users_visibility_script
    self.update_all(:visibility => true)
  end


  # --- Image cropping methods
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def reprocess_avatar
    image.reprocess! :small
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.url(:original))
    # @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end

end
# return the comparison result

app/controllers/tutor_profiles_controller.rb
class TutorProfilesController < ApplicationController
  autocomplete :tutor_profile, :teaching_subject
  before_action :set_tutor_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]



  def search
    @search_levels = params[:level]
    @search_subject = params[:search]
    @all_levels = Level.get_all_levels
    @filters = params.slice(:university)
    @all_tutors = TeachingSubject.get_all_teaching_subjects
    @countries = Country.all

    if params[:search].present? && params[:level].present?
      # both LEVEL and SUBJECT wise search
      @tutor_profiles = TutorProfile.get_all_subjects_with_levels(params[:search],params[:level])
    elsif params[:search].present?  && !params[:level].present?
      # only SUBJECT wise search
      @tutor_profiles = TutorProfile.get_matching_subject(params[:search])
    elsif params[:level].present? && !params[:search].present?
      # only LEVEL wise search
      @tutor_profiles = TutorProfile.get_matching_levels(params[:level])
    else
      @tutor_profiles = TutorProfile.where(:visibility => true).where(@filters).paginate(:page => params[:page], :per_page => 10)
    end

    if params[:search_university].present? && !@tutor_profiles.blank?
      tmp = []
      @tutor_profiles.each{|tp|(tmp << tp) if ( tp.university == params[:search_university] )}
      @tutor_profiles = tmp
    end

    if params[:search_city].present? && !@tutor_profiles.blank?
      tmp = []
      @tutor_profiles.each{|tp|(tmp << tp) if (tp.location_two==params[:search_city] || tp.location_city==params[:search_city])}
      @tutor_profiles = tmp
    elsif params[:search_country].present? && !@tutor_profiles.blank?
      tmp = []
      @tutor_profiles.each{|tp|(tmp << tp) if (tp.location==params[:search_country] || tp.country==params[:search_country])}
      @tutor_profiles = tmp
    end

  end

  def autocomplete
    render json: TutorProfile.where("teaching_subject LIKE :teaching_subject",  {teaching_subject: "%#{params[:search]}%"}).where(@filters)
  end

  def index
   @search_levels = params[:level]
    @search_subject = params[:search]
    @all_levels = Level.get_all_levels
    @filters = params.slice(:university)
    @all_tutors = TeachingSubject.get_all_teaching_subjects
    @universities = University.all
    @countries = Country.all


    if params[:search].present? && params[:level].present?
      # both LEVEL and SUBJECT wise search
      @tutor_profiles = TutorProfile.get_all_subjects_with_levels(params[:search],params[:level])
    elsif params[:search].present?  && !params[:level].present?
      # only SUBJECT wise search
      @tutor_profiles = TutorProfile.get_matching_subject(params[:search])
    elsif params[:level].present? && !params[:search].present?
      # only LEVEL wise search
      @tutor_profiles = TutorProfile.get_matching_levels(params[:level])
    else
      @tutor_profiles = TutorProfile.where(:visibility => true).where(@filters).paginate(:page => params[:page], :per_page => 10)
    end
  end

  def show
    if params[:search_levels].present?
      @message_subject = " #{params[:search_subject.capitalize]} #{params[:search_levels].to_sentence}를 가르쳐 주실 선생님을 찾고 있습니다."
    else
      @message_subject = "#{params[:search_subject]}를 가르쳐 주실 선생님을 찾고 있습니다."
    end
    @similar_users = []
    if params[:similar_profiles].present? # check for similar user types to send message inquiry
      similar_tutors = TutorProfile.find(params[:similar_profiles])
      @similar_users = similar_tutors.collect { |tp| tp.user.id }
    end

    @user = @tutor_profile.user
    @reviews = Review.where(tutor_profile_id: @tutor_profile.id).order("created_at DESC")
    if @reviews.blank?
      avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def new
    if current_user.tutor_profile.nil?
      @tutor_profile = TutorProfile.new
    else
      flash[:error] = "프로필이 이미 있습니다."
      redirect_to root_path
    end
  end

  # GET /tutor_profiles/1/edit
  def edit
  end

  # POST /tutor_profiles
  # POST /tutor_profiles.json
  def create
    tutor_profile_params["degree_subject"].downcase!
    tutor_profile_params["teaching_subject"].downcase!
    tutor_profile_params["teaching_subject_2"].downcase!
    tutor_profile_params["teaching_subject_3"].downcase!
    @tutor_profile = TutorProfile.new(tutor_profile_params)
    @tutor_profile.user_id = current_user.id

    respond_to do |format|
      if @tutor_profile.save
        MessageMailer.send_notification_on_tutor_create(current_user.email,@tutor_profile)
        format.html { redirect_to @tutor_profile, notice: '프로필이 성공적으로 만들어졌습니다.' }
        format.json { render action: 'show', status: :created, location: @tutor_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @tutor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutor_profiles/1
  # PATCH/PUT /tutor_profiles/1.json
  def update
    tutor_profile_params["degree_subject"].downcase!
    tutor_profile_params["teaching_subject"].downcase!
    tutor_profile_params["teaching_subject_2"].downcase!
    tutor_profile_params["teaching_subject_3"].downcase!
    respond_to do |format|
      if @tutor_profile.update(tutor_profile_params)
        format.html { redirect_to @tutor_profile, notice: '프로필이 성공적으로 업데이트 되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tutor_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutor_profiles/1
  # DELETE /tutor_profiles/1.json
  def destroy
    @tutor_profile.destroy
    respond_to do |format|
      format.html { redirect_to tutor_profiles_url }
      format.json { head :no_content }
    end
  end

  # review invitation link

  def invite_for_review
    if current_user.tutor_profile.present?
      @url = new_tutor_profile_review_url(current_user.tutor_profile)
    else
      flash[:error] = "선생님 프로필이 있어야 합니다."
      redirect_to :back
    end
  end

  def send_invitation_for_review
    if MessageMailer.send_invitation_for_review(params[:email],params[:first_name],params[:last_name],params[:message],params[:url],current_user.tutor_profile)
      flash[:notice] = "후기 요청을 보냈습니다."
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def send_user_specific_request_for_review
    @email = Tuition.find(params[:tuition_id]).user.email
    @url = new_tutor_profile_review_url(current_user.tutor_profile)
    if MessageMailer.send_user_specific_request_for_review(@email,@url,current_user.tutor_profile)
      flash[:notice] = "후기 요청을 보냈습니다."
    else
      flash[:error] = "후기 요청을 보낼수 없습니다. 이메일 주소를 한번 더 확인 해주십시요."
    end
    redirect_to :back
  end

  # /review invitation link

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tutor_profile
    @tutor_profile = TutorProfile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tutor_profile_params
    params.require(:tutor_profile).permit(:user_id, :university, :degree_subject, :teaching_subject, :teaching_subject_2, :teaching_subject_3, :location, :about_myself, :tutoring_approach, :teaching_experience, :extracurricular_interests, :image, :tutor_profile_id, :subject_level, :hourly_rate, :hours)
  end

  def check_user
    if current_user != @tutor_profile.user
      redirect_to root_url, alert: "죄송합니다. 이 프로필은 다른 분것입니다."
    end
  end
end

app/helpers/tutor_profiles_helper.rb
module TutorProfilesHelper
end

app/views/tutor_profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <h1>Editing tutor_profile</h1>
      </div>
    </div>

<%= render 'form' %>

<br><br>

    <div class="row">
    <div class="col-md-6 col-md-offset-2">
<%= link_to 'Show', @tutor_profile %> |
<%= link_to 'Back', tutor_profiles_path %>
      </div>
  </div>

app/views/tutor_profiles/invite_for_review.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">

      <%= form_tag(send_invitation_for_review_tutor_profiles_path, :method => :post ) do %>
        
        <br>
      <h2>후기 요청하기</h2>
      <br>

        <%= hidden_field_tag :url, @url %>
      
        <div class="row">
          <div class="col-lg-12">
            <%= label_tag "학생 이메일 주소 " %>
            <%= text_field_tag :email, nil, :class => "form-control pull-left" %>
          </div>
        </div>
        <br>

        <div class="row">
          <div class="col-lg-12">
            <%= label_tag "메세지"%>
            
            <%= label_tag do %>
                            
            <% end %>
            <%= label_tag do %>
              
              <% end %>
            <p>아래 메세지는 수정이 가능하며 입력된 이메일 주소로 발송이 되겠습니다. 이메일에는 후기를 남길 수 있는 링크가 포함되어 있습니다.</p>
            <%= text_area_tag :message, "그루미라는 과외 중개 웹사이트에 선생님으로 가입을 햇어~ 그루미에 있는 쌤 프로필에 후기 목록이 있는데 여기에 쌤과 했던 수업에 대한 후기를 남겨주면 많은 도움이 될거 같은데 가능할까? 아래 링크를 따라가서 로그인을 하고 후기 작성을 하면 끝!^^", :class => "form-control", :rows => 5 %>           
          </div>
        </div>

        <br>

        <div class="row">
          <div class="col-lg-2 col-lg-offset-10">
            <%= submit_tag "전송", :class => "btn btn-primary" %>
          </div>
        </div>

    <% end %>

    </div>
  </div>
</div>

app/views/tutor_profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <h3>Registering as a Tutor</h3>
      <p>Please fill out the following info that will be shown on your tutor profile. After you fill out this form, an email will be sent to you to schedule a brief phone interview to verify and confirm your tutorship with Young Tutors.</p>
    </div>
    </div>

    <%= render 'form' %>
    <br><br>

    <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <%= link_to 'Back', tutor_profiles_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/tutor_profiles/search.html.erb
<div class="searchresults">
  <div class="row">
    <div class="col-md-1 col-sm-2 col-xs-1"></div>
    <div class="col-md-7 col-sm-7 col-xs-10">
      <h2>
        <% if @search_levels.present? %>
        <span style="font-size:45px; color:white"><%= @search_levels.to_sentence %></span> <span style="font-size:45px; color:white"><%= @search_subject.capitalize %></span> 선생님들을 만나보세요!
        
        <% else %>
        <span style="font-size:45px; color:white"><%= @search_subject.capitalize %></span> 선생님들을 만나보세요!
        <% end %>
      </h2>
    </div>
  </div>
</div>
<div class="container profile">
  <br>  
<div class="row">
  <div class="col-md-3 col-sm-4" style="border-right: 2px solid #eee">
    <%= form_tag search_tutor_profiles_path, method: :get, class: "center" do %>
        <div class="row">
          <div class="col-lg-10">
            <%= select_tag :search, options_for_select(@all_tutors.map {|tt| [tt.split.map{ |w| ['and','or','of'].include?(w) ? w : w.capitalize}.join(' '),tt]}.insert(0, ["수업과목",nil])), :id => "e1", :style=>"width:100%;", :class => "form-control" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-lg-10">
            <div onclick="open">
              <h5>대입 준비</h5>
            </div>
            <div id="universityAdmissionLevels">
              <!---------------University level---------------->
                <% Level.university_admission_levels.each do |ual| %>
                  <%= check_box_tag "level[]", ual %> <%= ual %><br>
                <% end %>
              <!---------------/University level---------------->
            </div>
            <div id="examPreparation">
              <h5>시험 준비</h5>
            </div>
            <div id="examPreparationLevel">
              <!---------------Exam Preparation---------------->
                <% Level.exam_preparation_levels.each do |epl| %>
                  <%= check_box_tag "level[]", epl %> <%= epl %><br>
                <% end %>
              <!---------------/Exam Preparation---------------->
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-10"  style="margin-top: 10px;">
            <%= label_tag "희망 대학" %>
            <%= select_tag :search_university, options_for_select(University.all.map{|u| [u.name.capitalize,u.name]},(@tutor_profile.university rescue nil)), :include_blank => true, :id => "university", :class => "form-control" %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-10"  style="margin-top: 10px;">
            <%= label_tag "수업위치" %>
            <%= select_tag :search_country, options_for_select([[" 나라 선택",""]]+@countries.map{|c| [c.name.capitalize,c.name]}), :class => "form-control", :onchange=>"get_country_set_city(this.value)" %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-10" style="margin-top: 10px;">
            <div id="search_city_select">
              <%= select_tag :search_city, options_for_select([[" 도시 선택",""]]), :id => "e4", :class => "form-control indexsearchbox mrgtop10" %>
            </div>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-lg-10">
            <%= submit_tag "선생님 찾기", :name => nil, :class => "btn btn-primary pull-right" %>
          </div>
        </div>
    <% end %>
  </div>

  <!------------- Right Panel for search results------------>
  <% @all_profiles =  @tutor_profiles.collect{|tp|tp.id } %>

  <div class="col-md-9 col-sm-7">
    <% if @tutor_profiles.length > 0 %>
      <% @tutor_profiles.each do |tutor_profile| %>
        <div class="row">
          <div class="col-md-2 col-sm-4 col-xs-12">
            <%= link_to tutor_profile_path(:id => tutor_profile.id, :similar_profiles => @all_profiles-[tutor_profile.id], :search_levels => @search_levels, :search_subject => @search_subject) do %>
              <div class="round-avatar" style = 'background-image: url(<%= tutor_profile.image.url(:small) rescue "/assets/default.jpg" %>); background-size: 120px; margin-left:auto; margin-right:auto;'></div>
            <% end %>
            <% if tutor_profile.user==current_user %>
              <%= link_to '프로필 없애기', tutor_profile, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
          <div class="col-md-6 col-sm-8 col-xs-12">
            <%= link_to tutor_profile_path(:id => tutor_profile.id, :similar_profiles => @all_profiles-[tutor_profile.id], :search_levels => @search_levels, :search_subject => @search_subject) do %>
            <h3><%= "#{tutor_profile.user.first_name}" %></h3>
            <p>
              대학/전공: <%= tutor_profile.university.capitalize %>/ <%= tutor_profile.tutor_degree_subjects.first.degree_subject.capitalize unless tutor_profile.tutor_degree_subjects.blank?  %><br> 
              국내: <%= [tutor_profile.location_city,tutor_profile.location].join(" | ") %> <br>
              해외: <%= [tutor_profile.location_two,tutor_profile.country].join(" | ") %><br>
              수업과목: <%= tutor_profile.tutor_teaching_subjects.pluck(:teaching_subject).map { |ts| ts.capitalize}.join(", ") %>
            </p>
            <p style="font-size: 14px"><%= truncate(tutor_profile.about_myself, :length => 120) %></p>
            <div class="truncate"></div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="row">
        <div class="col-lg-12">
          <h2>Sorry we currently don't have any tutors for <%= @search_subject.capitalize %>.</h2> 
          <h3>Please let us know by contacting the <%= link_to "support team", contacts_path, class: "link" %> and we will find your desired tutor for you very shortly.</h3>
        </div>
      </div>
    <% end %>
  </div>
</div>
       
<br>
<br>
</div>

<style>
    .filter {
        color: black
    }
    .filter:hover {
        color: black
    }
</style>

<script>
  $(document).ready(function() { $("#e1").select2({placeholder: "Select subject", allowClear: true}); });
</script>

<script>
  function get_country_set_city(country_name){
    $.ajax({
      url: "<%= pages_get_country_set_city_path %>",
      method: "POST",
      data: {country_name : country_name},
      success:function(data){
        cities = data.cities
        options = '<option></option>'
        for(i=0;i<cities.length;i++){
          options = options + '<option value='+'"'+ cities[i]+'"' +'> ' + cities[i] + '</option>'
        }
        $("#search_city_select").html(
            '<select class="form-control" name="search_city" >'+
            options+
            '</select>'
        )
      }
    })
  }
</script>