config/routes.rb
Etsydemo::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :subjects

  resources :tutorships do
    collection do
      put :accept_tutorship, as: 'accept'
    end
  end

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  resources :questions do
    collection do
      post "create_question_comment" do
        post "create_question_comment_reply"
      end
    end
  end

  scope "(:locale)", locale: /en|ko|zh/ do
    
    resources :messages 

    resources :conversations do
      member do
        post :reply
        post 'trash'
      end
    end
    
    devise_for :users, :path_prefix => 'account', :controllers => { :registrations => "registrations" }
   
    resources :tutor_profiles do 
      get :autocomplete_tutor_profile_teaching_subject, :on => :collection
      collection do 
        get 'search'
        get 'reference'
        get 'invite_for_review'
        post 'send_invitation_for_review'
        get 'send_user_specific_request_for_review'
      end
      
      resources :tuitions do
        collection do
          get 'book_tuition'
          get 'payment_detail'
          post 'perform_transaction'
        end
      end
      resources :reviews, except: [:show, :index]
    end

    resources :new_tutor_profiles do
      collection do
        post 'update_tutor_profile'
      end
    end
  
    resources :enquiries 
    
    resources :users
  end

  get "pages/about"
  get 'mytuition' => "tuitions#mytuition"
  get "pages/inbox"
  get "pages/resources"
  get "pages/personal_statements"
  get "pages/college_essays"
  get "pages/oxbridge_interview_questions"
  get "pages/suggested_readings"
  get "pages/admissions_facts"
  get "pages/writing_personal_statements"
  get "pages/admissions_test"
  get "pages/written_work"
  get "pages/oxbridge_interviews"
  get "pages/students_parents"
  get "pages/services_for_schools"
  get "pages/partners"
  
  get "pages/how_it_works"
  get "pages/terms_and_conditions"
  get "pages/terms_and_conditions/for_tutors"
  get "pages/terms_and_conditions/for_students"
  get "pages/become_a_tutor"
  get "pages/referral_scheme"
  get "pages/tutor_policy"
  get "pages/free_consultation"
  get "pages/our_stars"
  get "pages/recruiting"
  get "pages/us_admissions"
  
  get "pages/about"
  get "pages/language_learning"
  get "pages/examinations"
  get "pages/online_tuition"
  get "pages/our_tutors"
  
  
  post "pages/get_town_from_country_for_step_1"
  post "pages/get_country_set_city"
  post "pages/get_city_set_town"
  
  get "admin/notify_users"
  post "admin/send_mail_to_users"
  get "admin/run_script"

  root 'pages#index'

  

end

app/models/tuition.rb
class Tuition < ActiveRecord::Base
  validates :hours, presence: true
  belongs_to :tutor_profile
  belongs_to :user
  after_create :leave_message

  def leave_message

    flag = false
    user = self.user
    tutor_profile_user = self.tutor_profile.user
    conversation = nil

    user.mailbox.conversations.each do |conv|
      if conv.participants.include?(tutor_profile_user)
        conversation = conv
        break
      end
    end

    if conversation.nil?
      # no conversation found
      user.send_message(tutor_profile_user, "Hi #{tutor_profile_user.first_name} #{tutor_profile_user.last_name},\n\n I have booked #{self.hours} hours with you. \n\n My email is : #{user.email}.", "Booking for tuition.")
    else
      user.reply_to_conversation(conversation, "Hi #{tutor_profile_user.first_name} #{tutor_profile_user.last_name},\n\n I have booked #{self.hours} hours with you. \n\n My email is : #{user.email}.")
      # conversation found
    end

  end

end

app/controllers/tuitions_controller.rb
class TuitionsController < ApplicationController
  before_action :set_tuition, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_tutor_profile, only: [:payment_detail]

  # GET /tuitions
  # GET /tuitions.json
  
  def mytuition
    if current_user.tutor_profile.present?
      @tuitions =
          Tuition.all.where(user_id: current_user.id).order("created_at DESC") + (Tuition.all.where(tutor_profile_id: current_user.tutor_profile.id).order("created_at DESC") if current_user.tutor_profile.present?)
    else
      @tuitions =
          Tuition.all.where(user_id: current_user.id).order("created_at DESC")
    end
  end
  
  def index
    @tuitions = Tuition.all
  end

  def book_tuition
    @tuition = Tuition.new
    @tutor_profile = TutorProfile.find(params[:tutor_profile_id])
  end

  def payment_detail
    validation_flag = false
    @tuition = current_user.tuitions.new(tuition_params)
    tuition_params.each do |key,value|
      if value.blank?
        validation_flag = true
      end
    end
    if validation_flag
      flash[:error] = "Please fill all the required fields."
      redirect_to :back
    end
    @tuition.tutor_profile_id = @tutor_profile.id
  end

  def perform_transaction
    Stripe.api_key = "sk_test_4Ld3SH8JuQyRKJYNTvAE2EIt"

    stripe_token = Stripe::Token.create(
        :card => {
            :number => payment_details_params[:credit_card_number],
            :exp_month => payment_details_params[:expiration_month],
            :exp_year => payment_details_params[:expiration_year],
            :cvc => payment_details_params[:cvv]
        },
    ) rescue false

    if stripe_token
      @tuition = Tuition.new(tuition_params)
      @tutor_profile = @tuition.tutor_profile
      transaction = Stripe::Charge.create(
          :amount => (@tutor_profile.hourly_rate).to_i*@tuition.hours*100 ,
          :currency => "GBP",
          :card => stripe_token[:id], # obtained from successful token response
      ) rescue false
      if transaction
        @tuition.payment_transaction = transaction[:id]
        @tuition.payment_amount = transaction[:amount]/100
        @tuition.save
flash[:notice] = "Transaction is successful. You have paid £#{'%.2f' % @tuition.payment_amount} to #{@tutor_profile.user.first_name} #{@tutor_profile.user.last_name} for #{@tuition.hours} hours."
        redirect_to tutor_profile_path(@tutor_profile)
      else
        flash[:error] = "Something went wrong and transaction is not performed. Please check your payment details OR contact GuruMe Support."
        redirect_to :back
      end
    else
      flash[:error] = "The Payment Information seems incorrect. Please Verify your payment details."
      redirect_to :back
    end
  end

  # GET /tuitions/1
  # GET /tuitions/1.json
  def show
  end

  # GET /tuitions/new
  def new
    @tuition = Tuition.new
    @tutor_profile = TutorProfile.find(params[:tutor_profile_id])
  end

  # GET /tuitions/1/edit
  def edit
  end

  # POST /tuitions
  # POST /tuitions.json
  def create
    @tuition = Tuition.new(tuition_params)
    @tuition.user_id = current_user.id
    
    @tutor_profile = TutorProfile.find(params[:tutor_profile_id])
    @tuition.tutor_profile_id = @tutor_profile.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]
    raise token.inspect

    begin
      charge = Stripe::Charge.create(
        :amount => (@tutor_profile.hourly_rate * 100).floor,
        :currency => "gbp",
        :card => token
        )
      flash[:notice] = "Thanks for booking!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end
    
    respond_to do |format|
      if @tuition.save
        format.html { redirect_to tutor_profile_path@tutor_profile, notice: 'Tuition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tuition }
      else
        format.html { render action: 'new' }
        format.json { render json: @tuition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tuitions/1
  # PATCH/PUT /tuitions/1.json
  def update
    respond_to do |format|
      if @tuition.update(tuition_params)
        format.html { redirect_to @tuition, notice: 'Tuition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tuition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuitions/1
  # DELETE /tuitions/1.json
  def destroy
    @tuition.destroy
    respond_to do |format|
      format.html { redirect_to tuitions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tuition
      @tuition = Tuition.find(params[:id]) rescue nil
    end

    def set_tutor_profile
      @tutor_profile = TutorProfile.find(params[:tutor_profile_id])
    end

    def payment_details_params
      params.permit(:credit_card_number,:cvv,:expiration_month,:expiration_year)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tuition_params
      params.require(:tuition).permit(:hours, :city, :note, :user_id, :tutor_profile_id, :payment_transaction, :payment_amount)
    end
end

app/helpers/tuitions_helper.rb
module TuitionsHelper
end

app/views/tuitions/_form.html.erb
<%= form_for([@tutor_profile, @tuition]) do |f| %>
  <% if @tuition.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@tuition.errors.count, "error") %> prohibited this tuition from being saved:</h4>

      <ul>
      <% @tuition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

<div class="row">
  <div class="col-md-4">
 
  <div class="form-group">
    <%= f.label :hours %><br>
    <%= f.number_field :hours, class:"form-control" %>
  </div>
  </div>
  <div class="col-md-8">
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class:"form-control" %>
  </div>
  </div>
</div>
  <div class="form-group">
    <%= f.label :note %><br>
    <%= f.text_area :note, class:"form-control" %>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-md-8">
        <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
      </div>
      <div class="col-md-4">
        <%= label_tag :card_code, "CVC" %>
        <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag nil, "Expiration Date" %>
    <div class="row">
      <div class="col-md-3">
        <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
      </div>
      <div class="col-md-3">
        <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
      </div>
    </div>
  </div>

  <div class="form-group">
     <%= f.submit "Complete Order", class: "btn btn-success" %>
  </div>
<% end %>

app/views/tuitions/book_tuition.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2 style="text-align:center">Book tuition with <% user = User.find(@tutor_profile.user_id)%> <%= user.first_name %><br>
      for <%= number_to_currency(@tutor_profile.hourly_rate, :unit => "&pound;".html_safe) %></h2>
<br>
      <%= form_for @tuition, :url => payment_detail_tutor_profile_tuitions_path, :method => :get do |f| %>

        <div class="row">
          <div class="col-lg-6">
            <%= f.label :hours %>
            <%= f.number_field :hours, :class=>"form-control" %>
          </div>
          <div class="col-lg-6">
            <%= f.label :city %>
            <%= f.text_field :city, :class=>"form-control" %>
          </div>
        </div>
       <br>
        <div class="row">
          <div class="col-lg-12">
            <%= f.label :note %>
            <%= f.text_area :note, :class=>"form-control", placeholder: "Any partcicular requests on how the tuition is to be conducted?" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-lg-6 col-lg-offset-6">
            <div style="float: right;">
              <%= f.submit "Proceed to Payment", :class => "btn btn-success" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tuitions/edit.html.erb
<h1>Editing tuition</h1>

<%= render 'form' %>

<%= link_to 'Show', @tuition %> |
<%= link_to 'Back', tuitions_path %>

app/views/tuitions/index.html.erb
<h1>Listing tuitions</h1>

<table>
  <thead>
    <tr>
      <th>Hours</th>
      <th>City</th>
      <th>Note</th>
      <th>User</th>
      <th>Tutor profile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tuitions.each do |tuition| %>
      <tr>
        <td><%= tuition.hours %></td>
        <td><%= tuition.city %></td>
        <td><%= tuition.note %></td>
        <td><%= tuition.user_id %></td>
        <td><%= tuition.tutor_profile_id %></td>
        <td><%= link_to 'Show', tuition %></td>
        <td><%= link_to 'Edit', edit_tuition_path(tuition) %></td>
        <td><%= link_to 'Destroy', tuition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tuition', new_tuition_path %>

app/views/tuitions/mytuition.html.erb
<div class="container">
   <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2 style="text-align:center">My Tuition</h2><br>
      <% if current_user.tutor_profile.present? %>
      <table class="table table-striped">
        <tr>
          <th>Student Name</th>
          <th>Subject</th>
          <th>Hours</th>
          <th>Contact Details</th>
          <th>Tuition Fee</th>
          <th>Reviews</th>
        </tr>
        <% @tuitions.each do |tuition| %>
        <tr>
          <td><% user = User.find(tuition.user_id) %><%= user.first_name.capitalize %> <%= user.last_name.capitalize %></td> 
          <td></td>
          <td><%= tuition.hours %></td>  
          <td></td>
          <td>&pound;<%= '%.2f' % tuition.payment_amount %></td>
          <td> <%= link_to "Request Review", send_user_specific_request_for_review_tutor_profiles_path(:tuition_id => tuition.id) %> </td>
        </tr>
      <% end %>
      </table>
      <% else %>
      <table class="table table-striped">
        <tr>
          <th></th>
          <th style="text-align: center">Tutor</th>
          <th>Subject</th>
          <th>Level</th>
          <th>Hours</th>
          <th>Contact Details</th>
          <th></th>
        </tr>
        <% @tuitions.each do |tuition| %>
        <tr>
          <td><% 
      tutor_profile = TutorProfile.find(tuition.tutor_profile_id) 
      user = User.find(tutor_profile.user_id) 
      %>
            <a href="/tutor_profiles/<%= tutor_profile.id %>">
              <div class="round-avatarmytuition" style = 'background-image: url(<%= tutor_profile.image.url rescue "default.jpg" %>);'></div>
            </a>
          <td><% 
      tutor_profile = TutorProfile.find(tuition.tutor_profile_id) 
      user = User.find(tutor_profile.user_id) 
      %>
          <%= user.first_name %> <%= user.last_name %></td>
          <td></td> 
          <td></td>
          <td><%= tuition.hours %></td>
        <td><%= user.email %></td>
          <td><%= link_to "Book Tuition", book_tuition_tutor_profile_tuitions_path(tutor_profile), class: "btn btn-danger", data: { no_turbolink: true } %></td> 
        </tr>
      <% end %>
      </table>
      <% end %>
     </div>
  </div>

<style>
.table th, td {
  font-family: adelle_ltlight;
  font-size: 18px;
  text-align:center;
  vertical-align: middle;
}
  
.table-striped {
  text-align:center;
  th, td {text-align:center;}
}
</style>

app/views/tuitions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-2">    
      <h1>Book tuition with <% user = User.find(@tutor_profile.user_id) 
  %> <%= user.first_name %></h1>
      for <h4><%= number_to_currency(@tutor_profile.hourly_rate) %></h4>

<%= render 'form' %>

<%= link_to 'Back', tutor_profile_path(@tutor_profile) %>
    </div>
  </div>

app/views/tuitions/payment_detail.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <h2 style="text-align:center">Payment for booking tuition<br>
        with <% user = User.find(@tutor_profile.user_id)%> <%= user.first_name %><br><%= number_to_currency(@tutor_profile.hourly_rate.to_i*@tuition.hours, :unit => "&pound;".html_safe ) %></h2>
<br>
      <%= form_for @tuition, :url => perform_transaction_tutor_profile_tuitions_path, :method => :post do |f| %>

          <%= f.hidden_field :hours %>
          <%= f.hidden_field :city %>
          <%= f.hidden_field :note %>
          <%= f.hidden_field :user_id %>
          <%= f.hidden_field :tutor_profile_id %>

          <div class="row">
            <div class="col-lg-12">
              <%= label_tag :credit_card_number %>
              <%= text_field_tag :credit_card_number, nil, :class=>"form-control" %>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-lg-6">
              <%= label_tag :expiration_date %>
              <div class="row">
                <div class="col-lg-6">
                  <%= select_tag :expiration_month, options_for_select([["January",1],["February",2],["March",3],["April",4],["May",5],["June",6],["July",7],["August",8],["September",9],["October",10],["November",11],["December",12]]), :class => "form-control" %>
                </div>
                <div class="col-lg-6">
                  <%= select_tag :expiration_year, options_for_select(Date.today.year..Date.today.year.to_i+20), :class => "form-control" %>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
                <%= label_tag :cvv %>
                <%= text_field_tag :cvv, nil, :class=>"form-control" %>
              </div>
          </div>
          <br>
          <div class="row">
            <div class="col-lg-6">
              <%= link_to "Back", :back, class: "linkbuttonb" %>
            </div>
            <div class="col-lg-6">
              <div style="float: right;">
                <%= f.submit "Pay", :class => "btn btn-success" %>
              </div>
            </div>
          </div>

      <% end %>

    </div>
  </div>
</div>

app/views/tuitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hours:</strong>
  <%= @tuition.hours %>
</p>

<p>
  <strong>City:</strong>
  <%= @tuition.city %>
</p>

<p>
  <strong>Note:</strong>
  <%= @tuition.note %>
</p>

<p>
  <strong>User:</strong>
  <%= @tuition.user_id %>
</p>

<p>
  <strong>Tutor profile:</strong>
  <%= @tuition.tutor_profile_id %>
</p>

<%= link_to 'Edit', edit_tuition_path(@tuition) %> |
<%= link_to 'Back', tuitions_path %>